import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const IMG={orange:"https://framerusercontent.com/images/gvDePnG7SFuMYRcLz8gds6FuqA.jpg?height=1067&width=1600",light:"https://framerusercontent.com/images/Kyen7mFblouHakJsJjmgR7i3Hc.jpg?height=1067&width=1600",dark:"https://framerusercontent.com/images/71pE2LDGiiOhjNUgW8mZXEjQk.jpg?height=1067&width=1600"};
const projects=[["01","Bloomberg / Film & Motion","Film · Motion","2026",IMG.orange,"A kinetic brand film built around speed, texture and controlled light."],["02","Kinetic Studies","Animation · Art Direction","2026",IMG.light,"Experimental motion studies for campaigns that need a stronger visual pulse."],["03","Campaign / Visual Direction","Campaign · Photography","2026",IMG.dark,"A visual system spanning stills, moving image and social cutdowns."],["04","After Dark","Editorial · Film","2026",IMG.orange,"An atmospheric editorial language made for culture-first brands."]];
const services=[["01","Animation","3D, 2D, motion systems, title design and frame-by-frame craft."],["02","Film","Commercials, branded films, documentaries, social campaigns and post."],["03","Photography","Campaign stills, portraits, product, editorial and production."],["04","Creative Direction","Concepts, visual identities, storyboards and end-to-end direction."],["05","Post Production","Edit, color, compositing, sound, finishing and delivery systems."],["06","Production","Crew, casting, locations, equipment and production management."]];
const links=[["/","Home"],["/work","Work"],["/services","Services"],["/about","About"],["/roster","Roster"],["/contact","Contact"]];
const go=p=>{location.hash=p;scrollTo({top:0,behavior:"instant"})};
function useRoute(){const[p,setP]=useState(()=>location.hash.slice(1)||"/");useEffect(()=>{const f=()=>setP(location.hash.slice(1)||"/");addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);return p}
function useReveal(){useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>o.observe(e));return()=>o.disconnect()},[])}
function Layout({children}){const[menu,setMenu]=useState(false),route=useRoute();useReveal();useEffect(()=>{const f=e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")};addEventListener("pointermove",f);return()=>removeEventListener("pointermove",f)},[]);return <div className="site"><div className="glow"/><div className="grain"/><div className="progress"/><header className="nav"><button className="logo" onClick={()=>go("/")}>OBLASIA<span>®</span></button><nav className={menu?"links open":"links"}>{links.map(([p,n])=><button className={route===p?"active":""} onClick={()=>{go(p);setMenu(false)}} key={p}>{n}</button>)}</nav><button className="menu" onClick={()=>setMenu(!menu)}><i/><i/></button><button className="navcta" onClick={()=>go("/contact")}>Start a project ↗</button></header><main>{children}</main><Footer/></div>}
function Footer(){return <footer className="footer"><div className="footTop"><div><small>OBLASIA® / GLOBAL STUDIO</small><h2>Make something<br/><em>impossible to ignore.</em></h2></div><button className="round" onClick={()=>go("/contact")}>↗</button></div><div className="footGrid"><div><small>Based between</small><b>USA · INDIA · GLOBAL</b></div><div><small>Email</small><b>HELLO@OBLASIA.STUDIO</b></div><div><small>Social</small><b>INSTAGRAM · VIMEO · LINKEDIN</b></div><div><small>© 2026 OBLASIA®</small><b>ALL RIGHTS RESERVED</b></div></div></footer>}
function Card({p,i=0}){return <article className={"card reveal d"+i} onClick={()=>go("/work/"+p[0])}><div className="cardImg"><img src={p[4]}/><span>{p[0]}</span><div>View case ↗</div></div><section><div><small>{p[2]}</small><h3>{p[1]}</h3></div><small>{p[3]}</small></section></article>}
function Home(){return <><section className="hero"><img src={IMG.orange}/><div className="heroShade"/><div className="heroCopy"><small className="reveal">GLOBAL STUDIO · USA FOCUS</small><h1 className="reveal d1">Stories that move<br/><em>at the speed</em><br/>of culture.</h1><div className="heroBottom reveal d2"><p>Animation · Film · Photography<br/>Creative direction · Production</p><button onClick={()=>document.querySelector("#intro").scrollIntoView({behavior:"smooth"})}>Scroll to enter ↓</button></div></div></section><section id="intro" className="paper section"><small>01 / WHAT WE DO</small><div className="split"><h2>Made<br/><em>to move.</em></h2><div><p className="lead">OBLASIA is an independent creative studio for brands that don't stand still.</p><p>We build films, animation and visual worlds with a sharp point of view — from first sketch to final frame.</p><button className="link" onClick={()=>go("/services")}>Explore capabilities ↗</button></div></div><div className="ribbon">{services.slice(0,4).map(s=><div key={s[0]}><small>{s[0]}</small><b>{s[1]}</b></div>)}</div></section><section className="section"><div className="head"><div><small>02 / SELECTED MOTION</small><h2>Frame by <em>frame.</em></h2></div><button className="link" onClick={()=>go("/work")}>View all work ↗</button></div><div className="grid">{projects.slice(0,3).map((p,i)=><Card p={p} i={i} key={p[0]}/>)}</div></section><div className="marquee"><div>ANIMATION · FILM · PHOTOGRAPHY · CREATIVE DIRECTION · PRODUCTION · ANIMATION · FILM · PHOTOGRAPHY · </div></div><section className="paper manifesto section"><small>03 / OUR APPROACH</small><h2>We don't chase<br/><em>attention.</em><br/>We earn it.</h2><div className="manifestoRow"><span>01</span><p>Concept over decoration.</p><span>02</span><p>Emotion over noise.</p><span>03</span><p>Craft all the way down.</p></div></section></>}
function Hero({k,title,text,img}){return <section className="pageHero"><div className="pageHeroImg" style={{backgroundImage:`url(${img})`}}/><div><small className="reveal">{k}</small><h1 className="reveal d1">{title}</h1><p className="reveal d2">{text}</p></div></section>}
function Work({detail}){if(detail){const p=projects.find(x=>x[0]===detail)||projects[0];return <><section className="detailHero" style={{backgroundImage:`url(${p[4]})`}}><div><small>CASE STUDY / {p[0]}</small><h1>{p[1]}</h1></div></section><section className="section detail"><div><small>PROJECT</small><p className="lead">{p[5]}</p></div><div><div className="facts"><span>Scope<b>{p[2]}</b></span><span>Year<b>{p[3]}</b></span><span>Studio<b>OBLASIA®</b></span></div><p>From first visual reference to final master, every frame was shaped to feel intentional, tactile and unmistakably alive. Replace this copy with the real production story, credits, campaign metrics and behind-the-scenes material.</p></div></section><div className="detailImg"><img src={p[4]}/></div><section className="section"><button className="link" onClick={()=>go("/work")}>← Back to selected work</button></section></>};return <><Hero k="02 / SELECTED WORK" title={<>Work that<br/><em>moves.</em></>} text="A growing archive of motion, image and ideas made for brands, artists and culture." img={IMG.light}/><section className="section all">{projects.map((p,i)=><Card p={p} i={i%3} key={p[0]}/>)}</section></>}
function Services(){return <><Hero k="03 / CAPABILITIES" title={<>One studio.<br/><em>Many frames.</em></>} text="Strategy, creative and production under one roof — with the flexibility to scale around the work." img={IMG.dark}/><section className="paper services">{services.map(s=><div className="service reveal" key={s[0]}><span>{s[0]}</span><h2>{s[1]}</h2><p>{s[2]}</p><b>↗</b></div>)}</section><section className="dark"><small>BUILT AROUND THE IDEA</small><h2>Bring us the brief.<br/><em>We'll find the frame.</em></h2><button onClick={()=>go("/contact")}>Start a project ↗</button></section></>}
function About(){return <><Hero k="04 / THE STUDIO" title={<>Small team.<br/><em>Big world.</em></>} text="Independent by design. Global by reach. OBLASIA brings directors, animators, photographers and producers together around the idea." img={IMG.orange}/><section className="paper section about"><div><small>THE POINT OF VIEW</small></div><div><p className="lead">The best work happens when craft and culture collide.</p><p>We keep the core team close and build the wider crew around each project. That means senior attention without agency layers — and access to the right talent when the brief gets ambitious.</p><div className="stats"><b>06<small>Core capabilities</small></b><b>∞<small>Creative directions</small></b><b>01<small>Obsessive standard</small></b></div></div></section><div className="band"><img src={IMG.light}/></div></>}
function Roster(){const people=["Directors","Animators","Editors","Photographers","DOPs","Voice Artists","Producers","Compositors"];return <><Hero k="05 / INDEPENDENT NETWORK" title={<>Make room for<br/><em>the makers.</em></>} text="Shooters, voice artists, editors, producers and every sharp freelance talent in between — if you make exceptional work, we want to know you." img={IMG.light}/><section className="section roster">{people.map((x,i)=><div className="rosterCard reveal" key={x}><small>0{i+1}</small><h2>{x}</h2><p>OPEN CALL / GLOBAL</p></div>)}</section><section className="dark"><small>JOIN THE ROSTER</small><h2>Good people make<br/><em>better work.</em></h2><a href="mailto:hello@oblasia.studio?subject=OBLASIA%20Roster">Introduce yourself ↗</a></section></>}
function Contact(){return <section className="contact paper"><div><small>06 / START A CONVERSATION</small><h1>Have a brief?<br/><em>Let's make it move.</em></h1><a href="mailto:hello@oblasia.studio">HELLO@OBLASIA.STUDIO ↗</a></div><div className="contactGrid"><div><small>For projects</small><b>HELLO@OBLASIA.STUDIO</b></div><div><small>For talent</small><b>ROSTER@OBLASIA.STUDIO</b></div><div><small>Network</small><b>USA · INDIA · GLOBAL</b></div></div></section>}
function App(){const r=useRoute();let p=r==="/" ? <Home/> : r==="/work"?<Work/>:r.startsWith("/work/")?<Work detail={r.split("/")[2]}/>:r==="/services"?<Services/>:r==="/about"?<About/>:r==="/roster"?<Roster/>:<Contact/>;return <Layout>{p}</Layout>}
createRoot(document.getElementById("root")).render(<App/>);
addEventListener("scroll",()=>{let m=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty("--scroll",m?scrollY/m*100:0)},{passive:true});
